version: "3.7"
services:
  app:
    build:
      args:
        user: libi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: scart
    container_name: scart-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - scart

  db:
    image: mysql:5.7
    container_name: scart-db
    restart: unless-stopped
    # ports:
    #   -"33061:3036"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - scart

  nginx:
    image: nginx:alpine
    container_name: scart-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - scart

  redis:
    image: "redis:latest"
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
    networks:
      - scart
networks:
  scart:
    driver: bridge